package rules.demo4

import twitter4j.Status
global org.slf4j.Logger logger

declare Status
    @role( event )
    @timestamp( createdAt )
    @expires( 1m )
end

rule "Count tweets in 10 seconds"
    duration( 10s )
when
    Number( $count : intValue ) from accumulate(
        Status() over window:time( 30s ) from entry-point "twitter",
        count(1) )
then
    logger.info( "Tweets in the last 30 seconds: {}" , $count );
end

